### ISSUE TITLE
Separar servicios de editar perfil y contraseña

### ISSUE THREAD

**Issue by Eldinosaur** [YadiraAllauca/ServiciosProyectoDAS#10]
### Modulo de editar informacion de usuario
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/82054019/5b78e980-5a93-4e39-bb13-795accfc973d)

> No contiene la contraseña

### Modulo de editar contraseña
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/82054019/6579fdb9-b55c-4412-9e0b-6ea376704748)

> Solo contiene la contraseña

**Comment by YadiraAllauca** [comment]
Se ha implementado lo solicitado, @Eldinosaur necesito la aprobación de fusionar los cambios en la rama develop
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/94416577/b24249ea-07fc-47d3-8e8d-4f0dfb894e8f)

**Comment by Eldinosaur** [comment]
- Cumple con lo solicitado
- Se autoriza la fusion a la rama develop

**Comment by YadiraAllauca** [comment]
Merge ejecutado
