### ISSUE TITLE
Cambio en recepcion de datos de variables

### ISSUE THREAD

**Issue by Eldinosaur** [YadiraAllauca/ServiciosProyectoDAS#15]
Solicito el cambio de tipo de recepcion de `$_POST` a `$_GET` en los servicios:
- listar buses por cooperativa 
- listar frecuencia cooperativa
- listar paradas
- listar para ventas
- listar ventas

Para poder generar las listas sin necesidad de botones extras

**Comment by YadiraAllauca** [comment]
Se ha implementado lo solicitado, @Eldinosaur necesito la aprobación de fusionar los cambios en la rama develop
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/94416577/4c3c8963-b988-472b-9fa2-18cd34ba71cd)

**Comment by Eldinosaur** [comment]
Cumple con lo solicitado
Aprobado para fusión
