### ISSUE TITLE
Retorno ID Compra

### ISSUE THREAD

**Issue by ThaisArm** [YadiraAllauca/ServiciosProyectoDAS#17]
Necesito que al generar una compra y se llame al servicio generarVenta.php me revuelva el ID de la compra generada com respuesta

**Comment by YadiraAllauca** [comment]
Se ha implementado lo solicitado, @ThaisArm  necesito la aprobación de fusionar los cambios en la rama develop
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/94416577/cdb6522f-c679-496d-8663-49b656118a64)

**Comment by ThaisArm** [comment]
Gracias acepto el cambio
