### ISSUE TITLE
Actualización de Servicios

### ISSUE THREAD

**Issue by ThaisArm** [YadiraAllauca/ServiciosProyectoDAS#19]
Se solicita una actualización completa de los servicios.

**Comment by YadiraAllauca** [comment]
Se han actualizado todos los servicios como se solicitó, @ThaisArm necesito que me confirmes la fusión de los cambios con la rama develop
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/94416577/92f374c2-6f12-4876-a428-60cae7b69695)

**Comment by ThaisArm** [comment]
Agradezco y acepto los cambios
