### ISSUE TITLE
Servicio de listar viaje por bus

### ISSUE THREAD

**Issue by Eldinosaur** [YadiraAllauca/ServiciosProyectoDAS#7]
Necesito un servicio que liste los viajes por bus para asignar paradas

**Comment by YadiraAllauca** [comment]
Se ha implementado lo solicitado, @Eldinosaur necesito la aprobación de fusionar los cambios en la rama develop.
Muestra de la consulta final:
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/94416577/fcc02593-09e0-4335-ad84-c91784764fa6)

**Comment by Eldinosaur** [comment]
- Aprobado
