### ISSUE TITLE
Mejorar servicio listar frecuencias

### ISSUE THREAD

**Issue by Eldinosaur** [YadiraAllauca/ServiciosProyectoDAS#8]
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/82054019/a38438d9-7df2-4704-86bb-3c893d432bdc)

- Necesito poder visualizar las ciudades en lugar de los id de origen y destino en lugar de los id de ciudad

> Porque el oficinista solo modifica el estado de la frecuencia

**Comment by YadiraAllauca** [comment]
Se ha implementado lo solicitado, @Eldinosaur necesito la aprobación de fusionar los cambios en la rama develop.
Muestra de la consulta final:
![image](https://github.com/YadiraAllauca/ServiciosProyectoDAS/assets/94416577/c53c71d6-2f5b-4e86-8246-0e226b1c64e0)

**Comment by Eldinosaur** [comment]
- Cumple con lo solicitado
- -Se aprueba la fusion
